#!/bin/sh

cat > $1.self-decrypt.sh << EOF
#!/bin/sh
FILE=\`echo \$0 | sed 's/.self-decrypt.sh\$//'\`
BASE64=\`awk '/^__BASE64_ENCRYPT_BELOW__/ {print NR + 1; exit 0; }' \$0\`
tail -n+\$BASE64 \$0 |\\
    openssl base64 -d |\\
    openssl enc -aes-256-cbc -salt -d -out \${FILE}.decrypted ||\\
    rm \${FILE}.decrypted
exit 0
__BASE64_ENCRYPT_BELOW__
EOF

openssl enc -aes-256-cbc -salt -in $1 | openssl base64 >> $1.self-decrypt.sh
